title: Victor Auyanet's website
url: "https://auyanet.com"
base_url:
google_tracking: false
#google_analytics_key: G-DT3SKFBBZW
#google_recaptcha_v2_site_key:

# Default description in social shares for the jekyll-seo-tag gem
description: Web developer with experience in Next.js, React, Drupal, Version control, Clean code and much more

# Author details for the jekyll-seo-tag gem
author:
  name: Victor Auyanet Vilabella
  email: victor@auyanet.com
  twitter: auyanetvictor # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Victor Auyanet Vilabella
  links:
    - https://github.com/VAuyanet/portfolio


timezone: Etc/GMT-1
locale: en_US

plugins:
  - "jekyll-seo-tag"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

#SASS
sass:
  style: compressed