title: Victor Auyanet
url: "http://auyanet.com"
base_url:
google_analytics_key: G-DT3SKFBBZW
google_recaptcha_v2_site_key: 6LdMv48cAAAAAMqA9tJppqZlp8VbwVTaeWCkyKg3

# Default description in social shares for the jekyll-seo-tag gem
description: Curriculum Vitae

# Author details for the jekyll-seo-tag gem
author:
  name:
  email:
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Victor Auyanet
  links:
    - https://github.com/VAuyanet/curriculum-vitae


timezone: Etc/UTC


plugins:
  - "jekyll-seo-tag"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

#SASS
sass:
  style: compressed